### ISSUE TITLE
感谢作者的付出

### ISSUE THREAD

**Issue by ShunbaoLi** [neesonqk/unLockMusic#10]
互联网因为作者这样的人而精彩
希望作者不吝赐教写一个教程，我也愿意贡献出自己的国内主机，为海外广大华人服务

**Comment by neesonqk** [comment]
个人的小流量主机带宽非常有限，使用人数一多非常容易阻塞，等有时间了我也写一下如何设置代理，你可以自己架设一个独立的代理体验一下
