### ISSUE TITLE
感谢作者的付出，不过好像又挂了

### ISSUE THREAD

**Issue by BtXin** [neesonqk/unLockMusic#11]
刚刚试了下，pac.onenorthtech.com和pac.unlockmusic.us都502了。
另外不考虑开个支付宝二维码给我们个途径支持一下吗。

**Comment by aa36** [comment]
我也是的，应该又挂了

**Comment by aa36** [comment]
每天都在用，真的很实用

**Comment by neesonqk** [comment]
服务器前几天宕机了，没注意到，已经重启完毕。感谢支持！
