### ISSUE TITLE
请问在centos下如何使用PAC呢？

### ISSUE THREAD

**Issue by LS12tthappy** [neesonqk/unLockMusic#2]
由于我的服务器放在了HK，是centos6系统，纯命令行界面
因为网易云的地区限制获取不了音乐，而Google不到关于linux使用pac的信息。请问作者你有没有什么好的方法呢？

**Comment by neesonqk** [comment]
你说的linux使用pac是什么意思呢？是架设pac的服务器吗？

**Comment by LS12tthappy** [comment]
如何在centos命令行里部署使用这个unLockMusic PAC文件？

**Comment by neesonqk** [comment]
如果你想把这个pac配置到你的vps让其自动路由的话可以export到环境变量

`export http_proxy = 'pac_file_location'`

如果是部署架设pac服务器可以直接把server目录部署到你服务器就可以了。
