### ISSUE TITLE
并不是在海外，但是由于公司网络屏蔽，用这个似乎不行？

### ISSUE THREAD

**Issue by idelin** [neesonqk/unLockMusic#5]
rt

**Comment by neesonqk** [comment]
有可能是因为速度慢的原因，如果设置后搜索显示正常的话就是速度的问题。

不过代理是先走国外的服务器的，有可能你的网络到国外第一级代理的速度很慢的原因。

**Comment by neesonqk** [comment]
Closed due to no active.
