### ISSUE TITLE
The pac link was broken, 502 Bad Gateway

### ISSUE THREAD

**Issue by yanhao-li** [neesonqk/unLockMusic#6]
It seems that the link serve the pac file was broken, could you fix it these days when you are available?
By the way, how did you set up the proxy server? I tried set up one with squid in my own server located in mainland.
The IP test passed (I used http://ipservice.163.com/isFromMainland), but still cannot use the music services(both on client and web). Could you please give some ideas how to do this?

**Comment by neesonqk** [comment]
It should work now, server went corrupt last night. 

About proxy server, I'm not very sure about your architecture, if your squid configured properly, I think it would work basically,  but I'd like to tell that you must set pass rule or allowed IP to your proxy server/squid, else it will expose your proxy service to everyone, which will jam your connection traffic.
